version: '3'

services:

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
      - 10000:10000
    volumes:
      - ./client:/app

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/server

  nginx:
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - 443:443
      depends_on:
        - server
        - client
