FROM debian:buster

# Install packages and download nginx source
RUN apt update && \
    apt install wget build-essential libpcre3 libpcre3-dev libssl-dev -y && \
    wget http://nginx.org/download/nginx-1.17.4.tar.gz && \
    tar -zxvf nginx-1.17.4.tar.gz && \
    mv nginx-1.17.4 nginx-src

# Configure and build nginx
WORKDIR /nginx-src
RUN ./configure \
    --sbin-path=/usr/bin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --with-pcre \
    --with-http_v2_module \
    --with-http_ssl_module \
    --without-http_gzip_module \
    --pid-path=/var/run/nginx.pid && \
    make && make install

COPY ./nginx.conf /etc/nginx/nginx.conf

# Generate self-signed SSL certificate
RUN mkdir /etc/nginx/ssl && \
    openssl req -x509 -days 10 -nodes -newkey rsa:2048 -keyout /etc/nginx/ssl/self.key -out /etc/nginx/ssl/self.crt \
    -subj "/C=DE/ST=HH/L=./O=./OU=./CN=."

CMD ["nginx" , "-g", "daemon off;"]